name: New Application
on:
  workflow_dispatch:
    inputs:
      name:
        description: The app name
        required: true
        type: string
      org_id:
        description: The org to create the app in
        required: true
        type: string
      owner:
        description: The owner id
        required: true
        type: string
      run-id:
        description: The run id passed in from the Humanitec Pipeline
        required: false
        default: unknown
        type: string

jobs:
  main:
    env:
      HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_DEV_TOKEN }}
      HUMANITEC_ORG: ${{ inputs.org_id }}
    runs-on: ubuntu-latest
    steps:
      - uses: humanitec/setup-cli-action@v1
      - run: 'humctl create app "${{ inputs.name }}"'
      - run: |
          humctl api post "/orgs/${{ env.HUMANITEC_ORG }}/apps/${{ inputs.name }}/users" -d '{"id": "${{ inputs.owner }}", "role": "owner"}'
      - run: 'humctl create env staging --type staging --app "${{ inputs.name }}"'
      - run: 'humctl create env production --type production --app "${{ inputs.name }}"'
