name: Link Resource Definition
on:
  workflow_dispatch:
    inputs:
      org_id:
        description: The org to create the app in
        required: true
        type: string
      app_id:
        description: The app id
        required: true
        type: string
      env_id:
        description: The env id
        required: true
        type: string
      run-id:
        description: The run id passed in from the Humanitec Pipeline
        required: false
        default: unknown
        type: string

jobs:
  main:
    env:
      HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
      HUMANITEC_ORG: ${{ inputs.org_id }}
    runs-on: ubuntu-latest
    steps:
      - uses: humanitec/setup-cli-action@v1
        with:
          version: '0.32.0'
      - run: |
          humctl api post /orgs/${{ env.HUMANITEC_ORG }}/resources/defs/my-fake-pg/criteria -d '{"app_id": "${{ inputs.name }}", "env_id": "${{ inputs.env_id }}"}'
      - run: >-
          delta_id=$(humctl api post /orgs/${{ env.HUMANITEC_ORG }}/apps/${{ inputs.app_id }}/deltas -d '{"metadata":{"env_id":"${{ inputs.env_id }}"}, "modules":{"update":{"${{ inputs.app_id }}-app":[{"op":"add","path":"/externals/db","value":{"type":"postgres"}},{"op":"add","path":"/spec/containers/main/variables/PSQL_CONNECTION","value":"postgresql://${externals.db.username}:${externals.db.password}@${externals.db.host}:${externals.db.port}/${externals.db.name}"}]}}}' | jq -r '.id' );
          echo ${delta_id};
          humctl deploy --org ${{ inputs.org_id }} --app ${{ inputs.app_id }} --env ${{ inputs.env_id }} delta ${delta_id} .
