name: Promote Environment
on:
  workflow_dispatch:
    inputs:
      org_id:
        description: The org to create the app in
        required: true
        type: string
      app_id:
        description: The app id
        required: true
        type: string
      source_env_id:
        description: The source env id
        required: true
        type: string
      target_env_id:
        description: The target env id
        required: true
        type: string
      run-id:
        description: The run id passed in from the Humanitec Pipeline
        required: false
        default: unknown
        type: string

jobs:
  main:
    env:
      HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
      HUMANITEC_ORG: ${{ inputs.org_id }}
    runs-on: ubuntu-latest
    steps:
      - uses: humanitec/setup-cli-action@v1
        with:
          version: '0.32.0'
      - run: humctl get app --org ${{ inputs.org_id }} ${{ inputs.app_id }}
      - run: humctl get env --org ${{ inputs.org_id }} --app ${{ inputs.app_id }} ${{ inputs.source_env_id }}
      - run: humctl get env --org ${{ inputs.org_id }} --app ${{ inputs.app_id }} ${{ inputs.target_env_id }}
      - run: humctl deploy ${{ inputs.org_id }} --app ${{ inputs.app_id }} env ${{ inputs.source_env_id }} ${{ inputs.target_env_id }} --wait
